###
GET http://localhost:8080/api/currencies

###
POST http://localhost:8080/api/currencies
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/api/currencies
Content-Type: application/x-www-form-urlencoded

name = Australian dollar &
sign =A$



###
POST http://localhost:8080/api/currencies
Content-Type: application/x-www-form-urlencoded


code = AUD &
name = Australian dollar &
sign = A$

###
POST http://localhost:8080/api/currencies
Content-Type: application/x-www-form-urlencoded

code = TES &
name = test1 &
sign = T

###
POST http://localhost:8080/api/currencies
Content-Type: application/x-www-form-urlencoded

code = TSE &
name = test2 &
sign = T

###
GET http://localhost:8080/api/currency/BYN

###
GET http://localhost:8080/api/currency/US

###
GET http://localhost:8080/api/currency/

###
GET http://localhost:8080/api/currency/EUR


###
GET http://localhost:8080/api/exchangeRates

###
POST http://localhost:8080/api/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode = TES &
targetCurrencyCode = TSE &
rate = 1.2534

###
PATCH http://localhost:8080/api/exchangeRate/TESTSE
Content-Type: application/x-www-form-urlencoded

rate=1.535


# exchangeRate by Codes
###
GET http://localhost:8080/api/exchangeRate/USDRUB

###
GET http://localhost:8080/api/exchangeRate/USDRUK

###
GET http://localhost:8080/api/exchangeRate/USDR

###
GET http://localhost:8080/api/exchangeRate/

###
GET localhost:8080/api/exchange?from=TES&to=TSE&amount=10
