###
GET http://localhost:8080/currencies

###
POST http://localhost:8080/currencies
Content-Type: application/json

###
POST http://localhost:8080/currencies
Content-Type: application/json

{
  "name": "Australian dollar",
  "sign": "A$"
}


###
POST http://localhost:8080/currencies
Content-Type: application/json

{
  "id": 0,
  "code": "AUD",
  "name": "Australian dollar",
  "sign": "A$"
}

###
POST http://localhost:8080/currencies
Content-Type: application/json

{
  "id": 0,
  "code": "BYN",
  "name": "Belarussian Ruble",
  "sign": "B₽"
}


###
GET http://localhost:8080/currency/BYN

###
GET http://localhost:8080/currency/US

###
GET http://localhost:8080/currency/

###
GET http://localhost:8080/currency/EUR


###
GET http://localhost:8080/exchangeRates





# exchangeRate by Codes
###
GET http://localhost:8080/exchangeRate/USDRUB

###
GET http://localhost:8080/exchangeRate/USDRUK

###
GET http://localhost:8080/exchangeRate/USDR

###
GET http://localhost:8080/exchangeRate/
