###
GET http://localhost:8080/currencies

###
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name = Australian dollar &
sign =A$



###
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

id = 0 &
code = AUD &
name = Australian dollar &
sign = A$

###
GET http://localhost:8080/currency/BYN

###
GET http://localhost:8080/currency/US

###
GET http://localhost:8080/currency/

###
GET http://localhost:8080/currency/EUR


###
GET http://localhost:8080/exchangeRates





# exchangeRate by Codes
###
GET http://localhost:8080/exchangeRate/USDRUB

###
GET http://localhost:8080/exchangeRate/USDRUK

###
GET http://localhost:8080/exchangeRate/USDR

###
GET http://localhost:8080/exchangeRate/
